.eslintignore
.github/codeql/codeql-config.yml
.github/pull_request_template.md
.github/workflows/codeql.yml
.github/workflows/run-tests.yaml
scripts/utils.js
test/scripts/mocks/body-with-marquee.html
test/scripts/mocks/body-without-marquee.html
test/scripts/mocks/body.html
test/scripts/mocks/head.html
test/scripts/utils.test.js
utils/utils.js

As described in title 🙂
Test URLs:
Before: https://main--events-milo--adobecom.hlx.page/t3/event/03-12-2024/chicago/il/adobe-events-seminar?martech=off
After: https://update-pr-template--events-milo--adobecom.hlx.page/t3/event/03-12-2024/chicago/il/adobe-events-seminar?martech=off

project ESLint clean up and PR template upload

---

blocks/event-info-component/event-info-component.css
blocks/event-info-component/event-info-component.js
blocks/form-handler/controllers/checkbox-component-controller.js
blocks/form-handler/form-handler.css
blocks/form-handler/form-handler.js
blocks/img-upload-component/img-upload-component.css
styles/styles.css

Reworked the decoration of event-info component to reflect updated design
Refactored the form-handler to support:
component controllers
first section to be form step header
Resolves (continuous): [MWPW-145236](https://jira.corp.adobe.com/browse/MWPW-145236)
Test URLs:
- Before: https://event-creation--events-milo--adobecom.hlx.page/event/create/dme?martech=off
- After: https://event-creation-form-refactor--events-milo--adobecom.hlx.page/event/create/dme?martech=off

Event creation form refactor

---

blocks/form-handler/form-handler.js

Test URLs:
- After: https://gbajaj-event-creation-poc-fix--events-milo--adobecom.hlx.page/

Minor fixes to save data on backend/CAAS

---

blocks/event-format-component/event-format-component.css
blocks/event-format-component/event-format-component.js

Support for Minor changes in Docx. for moving new series table one row up.
Test URLs:
- Before: https://event-creation--events-milo--adobecom.hlx.page/event/create/dme?martech=off
- After: https://gbajaj-minor-fix--events-milo--adobecom.hlx.page/event/create/dme?martech=off

Gbajaj minor fix

---

blocks/event-map/event-map.css
blocks/event-map/event-map.js
utils/content-update.js

Switched to using google MAP Static API
Resolves: [MWPW-144888](https://jira.corp.adobe.com/browse/MWPW-144888)
TODO: swap out my own API key
Test URLs:
- Before: https://main--events-milo--adobecom.hlx.page/event/t3/03-22-2024/chicago/il/create-now-chicago-dme?martech=off
- After: https://google-map-static--events-milo--adobecom.hlx.page/event/t3/03-22-2024/chicago/il/create-now-chicago-dme?martech=off

Google map static

---

blocks/event-product-blades/event-product-blades.css
blocks/event-product-blades/event-product-blades.js
utils/content-update.js

Added a product-blades wrapper block with mock metadata
Resolves: [MWPW-151817](https://jira.corp.adobe.com/browse/MWPW-151817)
Test URLs:
Before: https://stage--events-milo--adobecom.hlx.page/drafts/qiyundai/details-page
After: https://product-blades--events-milo--adobecom.hlx.page/drafts/qiyundai/details-page

Product blades

---

blocks/event-agenda/event-agenda.css
blocks/event-agenda/event-agenda.js
blocks/event-map/event-map.css
blocks/event-map/event-map.js
utils/utils.js

Added basic agenda block with mock metadata
Resolves: [MWPW-148511](https://jira.corp.adobe.com/browse/MWPW-148511)
Test URLs:
- Before: https://stage--events-milo--adobecom.hlx.page/drafts/qiyundai/details-page
- After: https://event-agenda--events-milo--adobecom.hlx.page/drafts/qiyundai/details-page

Event agenda

---

blocks/events-form/events-form.css
blocks/events-form/events-form.js
styles/styles.css
utils/content-update.js
utils/utils.js

Added metadata filtering for RSVP form
Resolves: [MWPW-148336](https://jira.corp.adobe.com/browse/MWPW-148336)
Test URLs:
- After: https://events-form-update--events-milo--adobecom.hlx.page/

Events form update

---

blocks/events-form/events-form.js

Resolves: [MWPW-145669](https://jira.corp.adobe.com/browse/MWPW-145669)
Test URLs:
- After: https://mwpw-145669--events-milo--adobecom.hlx.page/drafts/cano/details-page#rsvp-form

MWPW-145669: disabled IMS profile matching fields

---

blocks/event-partners/event-partners.js
blocks/events-form/events-form.js
scripts/utils.js
utils/content-update.js

The newest details page now is error free and able to render images from the photos bag
Resolves: [MWPW-148212](https://jira.corp.adobe.com/browse/MWPW-148212)
Test URLs:
- Before: https://main--events-milo--adobecom.hlx.page/events/create-now/embrace-generative-ai-jun21/lehi/utah/2024-06-29?martech=off
- After: https://data-parsing-enhancement--events-milo--adobecom.hlx.page/events/create-now/embrace-generative-ai-jun21/lehi/utah/2024-06-29?martech=off

fixed partner, image content update logic

---

blocks/profile-cards/profile-cards.js
utils/content-update.js

Bug fix 6/26

---

events/blocks/bento-cards/bento-cards.css
events/blocks/prefile-cards-refactor/profile-cards-refactor.js
events/features/milo-carousel.js
events/scripts/scripts.js

Since we did the whole scripts and utils refactor, we had a small issue with some leftover miloConfig imports. This is to fix it and all of its side effects
Test URLs:
- After: https://milo-config-bug-fix--events-milo--adobecom.hlx.page/

Milo config caused bug fix

---

events/scripts/esp-controller.js

Updating ESL / ESP dev and stage endpoints based on https://wiki.corp.adobe.com/display/WCMSOps/Tier3+Event+Application+Stack#Tier3EventApplicationStack-Stage
Test URLs:
- After: https://esl-endpoint-update--events-milo--adobecom.hlx.page/

ESL endpoint update

---

events/blocks/event-schema/event-schema.js
events/scripts/content-update.js

Resolves: [MWPW-154576](https://jira.corp.adobe.com/browse/MWPW-154576)
Test URLs:
- After: https://schema-fix--events-milo--adobecom.hlx.page/

Fix event details page url in page schema

---

events/blocks/event-partners/event-partners.js
events/scripts/content-update.js
events/styles/styles.css

Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/bug-bash-3-test/san-jose/ca/2024-07-20
- After: https://bugbash-7-18--events-milo--adobecom.hlx.page/events/create-now/bug-bash-3-test/san-jose/ca/2024-07-20

Bugbash 7 18

---

events/blocks/events-form/events-form.js
events/blocks/preview-bar/preview-bar.js
events/scripts/esp-controller.js
events/scripts/scripts.js

Removed unusable sponsor calls helper functions
Added prod env for main branch
Changed events from split syntax to allow "," in options
Test URLs:
- After: https://ecc-env-fix--events-milo--adobecom.hlx.page/

ENV fix + Events Form split syntax fix + refactor

---

events/blocks/event-partners/event-partners.css
events/blocks/event-partners/event-partners.js

Resolves: [MWPW-153776](https://jira.corp.adobe.com/browse/MWPW-153776)
Test URLs:
- After: https://partner-layout-fix--events-milo--adobecom.hlx.page/

event-partners odd/even layout

---

events/blocks/event-schema/event-schema.js
events/blocks/profile-cards/profile-cards.js
events/scripts/content-update.js

Resolves: [MWPW-153776](https://jira.corp.adobe.com/browse/MWPW-153776)
Test URLs:
- After: https://fix-fetch-error--events-milo--adobecom.hlx.page/

Misc. FE bug fix

---

events/blocks/event-schema/event-schema.js
events/blocks/profile-cards/profile-cards.js
events/scripts/content-update.js

dev -> stage July 23rd #2

---

events/scripts/scripts.js

Test URLs:
- After: https://switch-branch--events-milo--adobecom.hlx.page/

become Milo main consumer again

---

events/scripts/scripts.js

become Milo main consumer again (#67)

---

events/blocks/profile-cards/profile-cards.js
events/scripts/esp-controller.js

Fixed speakerType reference
Fixed undefined image issue
Test URLs:

Profile cards fix

---

events/blocks/event-map/event-map.js

Test URLs:
- After: https://map-fix--events-milo--adobecom.hlx.page/

Map Image Condition to prevent false positive splunk report

---

events/blocks/event-map/event-map.js
events/blocks/profile-cards/profile-cards.js
events/scripts/esp-controller.js

Dev -> Stage July 26 #2

---

events/blocks/profile-cards/profile-cards.js

Profile Social Links key name change

---

events/blocks/profile-cards/profile-cards.js

* Update profile-cards.js
* Update profile-cards.js
Test URLs:

Profile Social Links key name change (#71)

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/styles/styles.css

Making some small changes to the RSVP modal styling after reviewing the figma
Resolves: [MWPW-148336](https://jira.corp.adobe.com/browse/MWPW-148336)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/harry-potter-day-on-july-25th/new-york/ny/2024-07-25?timing=1721949299990#rsvp-form-1
- After: https://rsvp-success-style--events-milo--adobecom.hlx.page/events/create-now/harry-potter-day-on-july-25th/new-york/ny/2024-07-25?timing=1721949299990#rsvp-form-1

Slight Tweak to RSVP modal styling

---

events/scripts/content-update.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-155419
Test URLs:
- After: https://rsvp-analytics-fix--events-milo--adobecom.hlx.page/

update daa-ll tag at RSVP status change

---

events/blocks/event-map/event-map.css
events/blocks/profile-cards/profile-cards.css
events/blocks/profile-cards/profile-cards.js
events/scripts/content-update.js
events/scripts/utils.js
events/styles/styles.css

Resolves:
https://jira.corp.adobe.com/browse/DOTCOM-130317
https://jira.corp.adobe.com/browse/DOTCOM-130191
https://jira.corp.adobe.com/browse/DOTCOM-127495
Test URLs:
- After: https://a11y-fix--events-milo--adobecom.hlx.page/

A11y fixes

---

events/blocks/event-map/event-map.js

Resolves: https://jira.corp.adobe.com/browse/DOTCOM-127461
Test URLs:
- After: https://venue-image-alt--events-milo--adobecom.hlx.page/

Adding map image alt text

---

events/scripts/content-update.js

Test URLs:
- After: https://qiyundai-patch-1--events-milo--adobecom.hlx.page/

Fix render blocking hard fail

---

fstab.yaml

Reverts adobecom/events-milo#81

Revert "Update fstab.yaml"

---

fstab.yaml

Reverts adobecom/events-milo#84

Revert "Revert "Update fstab.yaml""

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-map/event-map.css

Resolves: [DOTCOM-127061](https://jira.corp.adobe.com/browse/DOTCOM-127061)
Test URLs:
- After: https://DOTCOM-127061--events-milo--adobecom.hlx.page/

map and agenda blades spacing tweaking

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-map/event-map.css

dev -> stage: map and agenda blades spacing tweaking (#92)

---

events/blocks/profile-cards/profile-cards.css

Fixed mismatched border radius of profile cards
Resolves: https://jira.corp.adobe.com/browse/DOTCOM-127061
Test URLs:
- After: https://qa-retest-fixes--events-milo--adobecom.hlx.page/

QA retest fixes

---

events/blocks/preview-bar/preview-bar.css
events/blocks/preview-bar/preview-bar.js
events/scripts/content-update.js
events/scripts/esp-controller.js
events/scripts/scripts.js

Updated ESP API endpoint for production environments
Test URLs:
- After: https://api-endpoint-update--events-milo--adobecom.hlx.page/

prod API endpoint update

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js

Resolves: [DOTCOM-130365](https://jira.corp.adobe.com/browse/DOTCOM-130365)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123
- After: https://DOTCOM-130365--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123

Events Form Success Msg QA fixes

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/utils.js

Resolves:
[MWPW-156384](https://jira.corp.adobe.com/browse/MWPW-156384)
[MWPW-156383](https://jira.corp.adobe.com/browse/MWPW-156383)
Test URLs:
- After: https://rayyan-asks--events-milo--adobecom.hlx.page/

Dev QA bug fixes

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-156261](https://jira.corp.adobe.com/browse/MWPW-156261)
Test URLs:
- After: https://MWPW-156261--events-milo--adobecom.hlx.page/

[MWPW-156261] Adding DAA tags to Events Form after profile's been loaded.

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-156530](https://jira.corp.adobe.com/browse/MWPW-156530)
Test URLs:
- After: https://mwpw-156530--events-milo--adobecom.hlx.page/

Fixing RSVP form invalid options issue

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/esp-controller.js
events/scripts/profile.js
test/unit/scripts/esp-controller.test.js

Resolves: [MWPW-156179](https://jira.corp.adobe.com/browse/MWPW-156179)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123
- After: https://attendee-api-revamp--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123

Attendee API revamp

---

events/scripts/esp-controller.js

fixing Attendee ESP controller refactor typos
Test URLs:

Dev -> Stage Aug 14th #2

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-156800](https://jira.corp.adobe.com/browse/MWPW-156800)
Test URLs:
- After: https://rsvp-form-fields-fix--events-milo--adobecom.hlx.page/

Fixing required fields not validating correctly

---

events/blocks/events-form/events-form.css

Resolves: [MWPW-156818](https://jira.corp.adobe.com/browse/MWPW-156818)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123#rsvp-form-1
- After: https://mwpw-156818--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123#rsvp-form-1

[MWPW-156818] RSVP form disabled fields updated UI

---

events/blocks/events-form/events-form.js
events/scripts/esp-controller.js

Resolves FE side of: [MWPW-156797](https://jira.corp.adobe.com/browse/MWPW-156797)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.live/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123&martech=off
- After: https://attendee-hotfix--events-milo--adobecom.hlx.live/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123&martech=off

RSVP Attendee API Hotfix

---

events/blocks/events-form/events-form.css

Dev -> Stage #2 Aug 16
Test URLs:

Dev -> Stage

---

events/scripts/content-update.js
events/scripts/scripts.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-156944
Test URLs:
- After: https://metadata-split--events-milo--adobecom.hlx.page/

[MWPW-156944] Metadata split

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/styles/styles.css

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER) pending
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/harry-potter-day-q-july-11th-again/new-york/ny/2024-08-24?previewMode=true&cachebuster=1724102216743&timing=1725024599990
- After: https://waitlist-fix--events-milo--adobecom.hlx.page/events/create-now/harry-potter-day-q-july-11th-again/new-york/ny/2024-08-24?previewMode=true&cachebuster=1724102216743&timing=1725024599990

Waitlist MVP scope fix

---

events/scripts/content-update.js

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER) Pending
Test URLs:
- After: https://tabindex-fix--events-milo--adobecom.hlx.page/

Fixing tabindex typo

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/scripts.js
events/styles/styles.css

Dev -> Stage Aug 20th

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js

Fixes a faulty RSVP status logic tree
Test URLs:
- After: https://waitlist-hotfix--events-milo--adobecom.hlx.page/

waitlist hotfix

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js

Resolves [MWPW-153570](https://jira.corp.adobe.com/browse/MWPW-153570)
Test URLs:

waitlist hotfix (#119)

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-157290](https://jira.corp.adobe.com/browse/MWPW-157290)
Test URLs:
- After: https://MWPW-157290--events-milo--adobecom.hlx.page/

Fix RSVP form sending empty values for optional fields bug

---

events/scripts/content-update.js

Resolves: [MWPW-152549](https://jira.corp.adobe.com/browse/MWPW-152549)
Test URLs:
- After: https://mwpw-152549--events-milo--adobecom.hlx.page/

[MWPW-152549] Updated Dynamic SUSI Context

---

events/scripts/content-update.js

Resolves: [MWPW-157031](https://jira.corp.adobe.com/browse/MWPW-157031)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27
- After: https://mwpw-157031--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27

[MWPW-157031] Added more context to mailto links

---

events/blocks/daa-injection/daa-injection.css
events/blocks/daa-injection/daa-injection.js
events/scripts/content-update.js
events/scripts/scripts.js
test/unit/blocks/daa-injection/daa-injection.test.js
test/unit/blocks/daa-injection/mocks/default.html
test/unit/blocks/daa-injection/mocks/no-target.html

This PR introduces a new block called daa-injection
First row of this block adjusts the daa-lh tag of the **next block**
The remaining config rows will adjust the daa-ll tags of links that match the url of each row's key column
The block will remove itself after finishing the job
Resolves: [MWPW-156261](https://jira.corp.adobe.com/browse/MWPW-156261)
Test URLs:
- After: https://daa-injection--events-milo--adobecom.hlx.page/

[NEW BLOCK] DAA injection

---

events/blocks/events-form/events-form.css

Resolves: [MWPW-157541](https://jira.corp.adobe.com/browse/MWPW-157541)
Test URLs:
- After: https://mwpw-157541-mini--events-milo--adobecom.hlx.page/

[MWPW-157541][PARTIAL] Update events-form submit button style

---

events/scripts/scripts.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-157870
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123
- After: https://title-fix--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123

Remove faulty fallback logic for title

---

events/scripts/constances.js
events/scripts/content-update.js
events/scripts/scripts.js

Resolves: [MWPW-152549](https://jira.corp.adobe.com/browse/MWPW-152549)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123&milolibs=custom-susi
- After: https://mwpw-152549-1--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123&milolibs=custom-susi

[MWPW-152549] Constances extraction and susiContexts to miloConfig

---

events/create-now/sitemap-index.xml
events/scripts/constances.js
events/scripts/content-update.js
events/scripts/scripts.js
helix-sitemap.yaml

Dev -> Stage 9/5/2024

---

events/scripts/content-update.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-158126
Test URLs:
- After: https://let-todd-see-events--events-milo--adobecom.hlx.page/

Add lowercasing for event preview email suffix check

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-158124](https://jira.corp.adobe.com/browse/MWPW-158124)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123&devMode=true#rsvp-form-1
- After: https://mwpw-158124--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123&devMode=true#rsvp-form-1

[MWPW-158124] Don't create empty key in payload for check and select

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-158400](https://jira.corp.adobe.com/browse/MWPW-158400)
Test URLs:
- After: https://mwpw-158400--events-milo--adobecom.hlx.page/

[MWPW-158400] Milo Form Validation Regression Fix

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-158400](https://jira.corp.adobe.com/browse/MWPW-158400)
Test URLs:

Dev -> Stage [MWPW-158400] Milo Form Validation Regression Fix (#156)

---

events/scripts/content-update.js

Resolves: [MWPW-158781](https://jira.corp.adobe.com/browse/MWPW-158781)
Test URLs:
- After: https://no-cache--events-milo--adobecom.hlx.page/

Adding cache control to mitigate event update delay

---

events/blocks/profile-cards/profile-cards.js

Resolves: [MWPW-158424](https://jira.corp.adobe.com/browse/MWPW-158424)
Test URLs:
- After: https://mwpw-158424--events-milo--adobecom.hlx.page/

[MWPW-158424] making bio optional

---

events/scripts/esp-controller.js

Test URLs:
- After: https://x-api-key--events-milo--adobecom.hlx.page/

Add x-api-key header

---

events/blocks/event-agenda/event-agenda.css
events/blocks/events-form/events-form.css
events/blocks/profile-cards/profile-cards.css
events/blocks/profile-cards/profile-cards.js

Resolves: [MWPW-158792](https://jira.corp.adobe.com/browse/MWPW-158792)
Test URLs:
- After: https://ui-bug-fix--events-milo--adobecom.hlx.page/

[MWPW-158792] UI Fine Tuning

---

events/scripts/content-update.js
events/scripts/esp-controller.js
events/scripts/scripts.js
events/scripts/utils.js
test/unit/scripts/esp-controller.test.js

Test URLs:
- After: https://ecc-env-refactor--events-milo--adobecom.hlx.page/

Split ECC ENV from Milo Config Env

---

events/scripts/utils.js

Test URLs:
- After: https://ecc-env-hotfix--events-milo--adobecom.hlx.page/

Ecc env hotfix

---

events/scripts/content-update.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-159558
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/harry-potter-day-preview-loading-dialog-poc-demo/rosemont/il/2024-09-29?previewMode=true&timing=1727668799990
- After: https://z-pattern-fix--events-milo--adobecom.hlx.page/events/create-now/harry-potter-day-preview-loading-dialog-poc-demo/rosemont/il/2024-09-29?previewMode=true&timing=1727668799990

Profile Cards Z pattern fix (Since Judges addition)

---

events/scripts/content-update.js

https://wiki.corp.adobe.com/display/adobedotcom/T3+Events+Weekly+Release-+Oct+2%2C+2024
Test URLs:

Dev -> Stage Oct 2nd 2024

---

events/scripts/content-update.js

Release note: https://wiki.corp.adobe.com/display/adobedotcom/T3+Events+Weekly+Release-+Oct+2%2C+2024
Test URLs:
- After: https://stage--events-milo--adobecom.hlx.page/

Stage -> Prod Thu 3 Oct. 2024

---

events/scripts/content-update.js
events/scripts/esp-controller.js

Resolves: [MWPW-160171](https://jira.corp.adobe.com/browse/MWPW-160171)
Test URLs:
- After: https://error-cleanup--events-milo--adobecom.hlx.page/

[MWPW-160171] Fixing Lana false positive errors

---

events/blocks/profile-cards/profile-cards.css

Resolves: [MWPW-160088](https://jira.corp.adobe.com/browse/MWPW-160088)
before:  <img width="444" alt="Screenshot 2024-10-08 at 9 34 51 AM" src="https://github.com/user-attachments/assets/b92191e8-3d4c-4544-9cf9-df395ed5739a">
after: <img width="437" alt="Screenshot 2024-10-08 at 9 34 30 AM" src="https://github.com/user-attachments/assets/16fc7b4b-cfe1-4c1e-95d5-e2d7dec64456">
Test URLs:
- After: https://mwpw-160088--events-milo--adobecom.hlx.page/

[MWPW-160088] profile cards spacing fix

---

events/blocks/event-schema/event-schema.js
events/scripts/content-update.js

Resolves: [MWPW-160284](https://jira.corp.adobe.com/browse/MWPW-160284)
Test URLs:
- After: https://mwpw-160284--events-milo--adobecom.hlx.page/

[MWPW-160284] Fix wrong title metadata references

---

.github/workflows/sync-branches.yml
events/scripts/esp-controller.js
events/scripts/utils.js

Resolves: [MWPW-160285](https://jira.corp.adobe.com/browse/MWPW-160285)
Test URLs:
- After: https://github-02-branches-sync-action--events-milo--adobecom.hlx.page/

[MWPW-160285] Create sync-branches.yml

---

.github/workflows/sync-branches.yml

Resolves: [MWPW-160285](https://jira.corp.adobe.com/browse/MWPW-160285)
Test URLs:
Before: https://dev--events-milo--adobecom.hlx.page/
After: https://github-02-branches-sync-action--events-milo--adobecom.hlx.page/

[MWPW-160285] Attempted fix to sync-branches.yml #1

---

events/blocks/profile-cards/profile-cards.js
events/scripts/content-update.js
events/scripts/esp-controller.js
events/scripts/profile.js
test/unit/blocks/profile-cards/mocks/default.html
test/unit/blocks/profile-cards/profile-cards.test.js
test/unit/scripts/content-update.test.js
test/unit/scripts/esp-controller.test.js
test/unit/scripts/mocks/head-5-blades.html
test/unit/scripts/mocks/head.html
test/unit/scripts/profile.test.js

Resolves: [MWPW-160717](https://jira.corp.adobe.com/browse/MWPW-160717)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/?martech=off
- After: https://unit-tests-2--events-milo--adobecom.hlx.page/?martech=off

[MWPW-160717] Unit tests > 90%

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/esp-controller.js
events/scripts/profile.js
events/scripts/scripts.js

This PR is the FE portion of the new RSVP waitlist integration.
Test URLs:
Before: https://dev--events-milo--adobecom.hlx.page/
After: https://mwpw-158803--events-milo--adobecom.hlx.page/

[MWPW-158800] RSVP waitlist changes

---

events/blocks/events-form/events-form.css

Test URLs:
- After: https://mwpw-158800--events-milo--adobecom.hlx.page/

[MWPW-158800] Better event form second screen alignment

---

events/scripts/content-update.js
events/scripts/esp-controller.js
test/unit/scripts/content-update.test.js

Test URLs:
- After: https://mwpw-158800-1--events-milo--adobecom.hlx.page/

[MWPW-158800] Rely on isFull for waitlist check

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/esp-controller.js

Test URLs:
- After: https://waitlist-cta--events-milo--adobecom.hlx.page/

[MWPW-158800] Dynamic Form CTA + x-request-id

---

events/scripts/esp-controller.js

Test URLs:
- After: https://qiyundai-patch-1--events-milo--adobecom.hlx.page/

[MWPW-158800] Sm fix for more consistent Reg flow

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-161044](https://jira.corp.adobe.com/browse/MWPW-161044)
Test URLs:
- After: https://MWPW-161044--events-milo--adobecom.hlx.page/

[MWPW-161044] Prompting SUSI for logged out users on #rsvp-form direct visit

---

events/blocks/events-form/events-form.js

Test URLs:
- After: https://mwpw-158800-follow--events-milo--adobecom.hlx.page/

[MWPW-158800] Follow: Fix Inaccurate Error Resp during RSVP

---

.github/workflows/sync-branches.yml
events/blocks/event-schema/event-schema.js
events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js
events/blocks/profile-cards/profile-cards.css
events/blocks/profile-cards/profile-cards.js
events/scripts/constances.js
events/scripts/content-update.js
events/scripts/esp-controller.js
events/scripts/profile.js
events/scripts/scripts.js
events/scripts/utils.js
test/unit/blocks/event-schema/event-schema.test.js
test/unit/blocks/profile-cards/mocks/default.html
test/unit/blocks/profile-cards/profile-cards.test.js
test/unit/scripts/content-update.test.js
test/unit/scripts/esp-controller.test.js
test/unit/scripts/mocks/head-5-blades.html
test/unit/scripts/mocks/head.html
test/unit/scripts/profile.test.js

https://wiki.corp.adobe.com/display/adobedotcom/T3+Events+Weekly+Release+-+Oct.+29%2C+2024
Test URLs:
- After: https://stage--events-milo--adobecom.hlx.page/

Stage -> Main Oct 29th

---

events/scripts/scripts.js

Resolves: [MWPW-161045](https://jira.corp.adobe.com/browse/MWPW-161045)
Test URLs:
- After: https://mwpw-161045--events-milo--adobecom.hlx.page/

[MWPW-161045] Reload page on token expiry

---

events/scripts/scripts.js

[MWPW-161045] Reload page on token expiry (#196 Dev -> Stage)

---

events/scripts/scripts.js

[MWPW-161045] Reload page on token expiry (#196) Dev -> Stage

---

events/scripts/esp-controller.js
events/scripts/scripts.js

Resolves: [MWPW-161940](https://jira.corp.adobe.com/browse/MWPW-161940)
Test URLs:
- After: https://endpoint-update-temp--events-milo--adobecom.hlx.page/

[CHORE] Updating Oregon temporary endpoints

---

events/blocks/events-form/events-form.js
events/scripts/scripts.js

Resolves: [MWPW-161877](https://jira.corp.adobe.com/browse/MWPW-161877)
Test URLs:
- After: https://events-form-full-prefill--events-milo--adobecom.hlx.page/

[MWPW-161877] Adding prefill from ESP fetched user data.

---

events/scripts/esp-controller.js

Resolves: [MWPW-162671](https://jira.corp.adobe.com/browse/MWPW-162671)
Test URLs:
Before: https://dev--events-milo--adobecom.hlx.page/
After: https://mwpw-162671--events-milo--adobecom.hlx.page/

[MWPW-162671] update stage02 endpoint

---

.github/pull_request_template.md
events/blocks/profile-cards/profile-cards.js
events/scripts/esp-controller.js
events/scripts/utils.js

Resolves: 
[MWPW-162622](https://jira.corp.adobe.com/browse/MWPW-162622)
[MWPW-162655](https://jira.corp.adobe.com/browse/MWPW-162655)
Test URLs:
- After: https://dev-debt--events-milo--adobecom.hlx.page/

Stop profile cards uncaught error + re-enable local dev env

---

events/blocks/events-form/events-form.js

Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/drafts/
- After: https://esp-provider-gone--events-milo--adobecom.hlx.page/drafts/

Prepare for ESL resp schema change

---

events/scripts/content-update.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-165264
Test URLs:
- After: https://jan-10-fixes--events-milo--adobecom.hlx.page/

Parse URL before trying to find non-prod data

---

helix-query.yaml

Resolves: https://jira.corp.adobe.com/browse/MWPW-162463
Test URLs:
- After: https://mps-helix-update--events-milo--adobecom.hlx.page/

Add consent-query-index

---

events/blocks/event-map/event-map.js

Test URLs:
- After: https://map-block-fix--events-milo--adobecom.hlx.page/

Remove Event Map Block Templating

---

events/blocks/event-map/event-map.js

Remove Event Map Block Templating (#223)

---

events/scripts/esp-controller.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-165787
Test URLs:
- After: https://mwpw-165787--events-milo--adobecom.hlx.page/

Call ESL for get Attendee

---

events/scripts/esp-controller.js

Test URLs:
- After: https://stage--events-milo--adobecom.hlx.page/

[Dev -> Stage] Call ESL for get Attendee (#226)

---

events/blocks/event-map/event-map.js
events/scripts/scripts.js

Adding required IMS configs for enabling guestToken
Resolves: [MWPW-160255](https://jira.corp.adobe.com/browse/MWPW-160255)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.live/
- After: https://guest-token-config--events-milo--adobecom.hlx.live/

Enable guestToken through IMS config

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-166361 
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/drafts/?martech=off
- After: https://events-multiselect--events-milo--adobecom.hlx.page/drafts/?martech=off

RSVP form upgrade - Support array output and correct rsvp attr key names

---

.github/pull_request_template.md
tools/sidekick/config.json

Test URLs:
- Before: https://main--events-milo--adobecom.hlx.page/drafts/
- After: https://sidekick-hotfix--events-milo--adobecom.hlx.page/drafts/

Sidekick Rollout Tool Hotfix

---

.github/pull_request_template.md
.github/workflows/update-pro-description.yml

Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.live/drafts/
- After: https://pr-description-job--events-milo--adobecom.hlx.live/drafts/

Adding Description Update Automation

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js
events/scripts/esp-controller.js
events/scripts/scripts.js
helix-query.yaml

Resolves: [MWPW-162463](https://jira.corp.adobe.com/browse/MWPW-162463)
Test URLs:
- Before: https://<BASE_BRANCH>--events-milo--adobecom.hlx.live/drafts/
- After: https://<TARGET_BRANCH>--events-milo--adobecom.hlx.live/drafts/

[MWPW-162463] RSVP with new consent strings

---

events/scripts/content-update.js

Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.live/drafts/
- After: https://add-404-redirect--events-milo--adobecom.hlx.live/drafts/

[DevOps] Force Lana load on 404 to explicitly log

---

.github/pull_request_template.md
.gitignore
events/scripts/content-update.js
events/scripts/utils.js
test/unit/blocks/daa-injection/mocks/default.html
test/unit/scripts/mocks/event-default-doc.html
tools/sidekick/config.json

Resolves: [MWPW-165532](https://jira.corp.adobe.com/browse/MWPW-165532)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/drafts/
- After: https://MWPW-165532--events-milo--adobecom.hlx.page/drafts/

[MWPW-165532] hlx5 updates

---

.github/pull_request_template.md
.gitignore
.kodiak/config.yaml
events/scripts/content-update.js
events/scripts/utils.js
test/unit/blocks/daa-injection/mocks/default.html
test/unit/scripts/mocks/event-default-doc.html
tools/sidekick/config.json

Dev to Stage | Feb 03

---

events/blocks/events-form/events-form.css
events/blocks/events-form/events-form.js

Test URLs:
- After: https://poi-field-hotfix--events-milo--adobecom.aem.live/drafts/

POI field hotfix

---

events/scripts/content-update.js
events/scripts/profile.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-168541
Test URLs:
- After: https://2-25-qa--events-milo--adobecom.aem.live/drafts/

Fix legacy cloud specific waitlist logic

---

events/blocks/event-agenda/event-agenda.css

Resolves: [MWPW-156859](https://jira.corp.adobe.com/browse/MWPW-156859)
Test URLs:
- After: https://gbajaj-agenda1--events-milo--adobecom.aem.live/drafts/

Minor css fixes for agenda

---

events/blocks/events-form/events-form.js
events/scripts/esp-controller.js

Resolves: [MWPW-168541](https://jira.corp.adobe.com/browse/MWPW-168541)
Test URLs:
- After: https://guest-checkout-fix--events-milo--adobecom.aem.live/drafts/

Fixing Guest Registration 403 Error

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-agenda/event-agenda.js
test/unit/blocks/event-agenda/event-agenda.test.js

Resolves: [MWPW-156859](https://jira.corp.adobe.com/browse/MWPW-156859)
Test URLs:
- After: https://gbajaj-agenda2--events-milo--adobecom.aem.live/drafts/

Agenda UI enhancements

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-168541](https://jira.corp.adobe.com/browse/MWPW-168541)
Test URLs:
- After: https://one-more-403--events-milo--adobecom.aem.live/drafts/

Fixing one more 403

---

events/blocks/events-form/events-form.js
helix-query.yaml

Resolves: https://jira.corp.adobe.com/browse/MWPW-168706
Test URLs:
- After: https://cs-fix--events-milo--adobecom.aem.live/drafts/

Remove consent string query indexing

---

events/blocks/event-agenda/event-agenda.js
test/unit/blocks/event-agenda/event-agenda.test.js

Test URLs:
- After: https://gbajaj-agenda3--events-milo--adobecom.aem.live/drafts/

Adding UTs for agenda

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js

Test URLs:
- After: https://rsvp-fix--events-milo--adobecom.aem.live/drafts/

FE fix for event is full logic

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js

Test URLs:
- After: https://rsvp-fix-2--events-milo--adobecom.aem.live/drafts/

Fixing on page load logic for full & no waitlist events

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/esp-controller.js

Test URLs:
- After: https://rsvp-fix-3--events-milo--adobecom.aem.live/drafts/

Fix Guest Cancellation

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
test/unit/scripts/content-update.test.js

Test URLs:
- After: https://rsvp-fix-4--events-milo--adobecom.aem.live/drafts/

fixed the RSVP cancellation issue without UT

---

events/scripts/content-update.js

Test URLs:
- After: https://rsvp-fix-last--events-milo--adobecom.aem.live/drafts/

Registration Close Fixed

---

events/scripts/content-update.js

[Dev -> Stage] Registration Close Fixed (#258)

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-agenda/event-agenda.js

Resolves: [MWPW-169187](https://jira.corp.adobe.com/browse/MWPW-169187)
Test URLs:
- After: https://gbajaj-MWPW169187--events-milo--adobecom.aem.live/drafts/

UI fixes for agenda line up

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-agenda/event-agenda.js

Resolves: [MWPW-156859](https://jira.corp.adobe.com/browse/MWPW-156859)
Test URLs:

[Dev -> Stage] UI fixes for agenda line up (#260)

---

events/blocks/events-form/events-form.js
events/scripts/esp-controller.js

Resolves: [MWPW-169249](https://jira.corp.adobe.com/browse/MWPW-169249)
Test URLs:
- After: https://waitlist-rsvp-fix--events-milo--adobecom.aem.live/drafts/

Fixing leftover event data references

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-agenda/event-agenda.js

[Dev -> Stage] Fixing leftover event data references

---

events/scripts/content-update.js

Test URLs:
- After: https://waitlist-fix2--events-milo--adobecom.aem.live/drafts/

Remove redundant event call and await

---

events/scripts/content-update.js

[Dev -> Stage] Remove redundant event call and await (#264)

---

events/scripts/content-update.js

Test URLs:
- After: https://cleanup--events-milo--adobecom.aem.live/drafts/

[CHORE] Remove deprecated devMode code

---

events/blocks/venue-additional-info/venue-additional-info.js

Resolves: [MWPW-160887](https://jira.corp.adobe.com/browse/MWPW-160887)
Test URLs:
- After: https://sin52605-MWPW-160887-bug-fix--events-milo--adobecom.aem.live/drafts/

fix metadata name

---

events/blocks/events-form/events-form.js

Resolves: [MWPW-169536](https://jira.corp.adobe.com/browse/MWPW-169536)
Test URLs:
- After: https://prefill-country--events-milo--adobecom.aem.live/drafts/

Prefill RSVP Form Country Input for Guests

---

events/scripts/content-update.js
test/unit/scripts/content-update.test.js

Test URLs:
- After: https://fix-hash-link-manipulation--events-milo--adobecom.aem.live/drafts/

Use more unique events placeholder link for auto remove identification

---

events/blocks/venue-additional-info/venue-additional-info.js

Resolves: [MWPW-160887](https://jira.corp.adobe.com/browse/MWPW-160887)
Test URLs:
- After: https://MWPW-160887-add-unpkg-version--events-milo--adobecom.aem.live/drafts/

Mwpw 160887 add unpkg version

---

events/blocks/event-map/event-map.js
events/blocks/venue-additional-info/venue-additional-info.js
test/unit/blocks/event-map/event-map.test.js

Resolves: [MWPW-160887](https://jira.corp.adobe.com/browse/MWPW-160887)
Test URLs:
- After: https://MWPW-160887-btn-fix--events-milo--adobecom.aem.live/drafts/

make sure we have content in venue additional modal before we show the button

---

events/blocks/venue-additional-info/venue-additional-info.js

Resolves: [MWPW-160887](https://jira.corp.adobe.com/browse/MWPW-160887)
Test URLs:
- After: https://MWPW-160887-html-version--events-milo--adobecom.aem.live/drafts/

MWPW-160887: html version of rte

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-agenda/event-agenda.js
events/blocks/event-map/event-map.js
events/blocks/events-form/events-form.js
events/blocks/venue-additional-info/venue-additional-info.css
events/blocks/venue-additional-info/venue-additional-info.js
events/scripts/content-update.js
test/unit/blocks/event-map/event-map.test.js
test/unit/blocks/event-map/mocks/default.html
test/unit/blocks/venue-additional-info/mocks/default.html
test/unit/blocks/venue-additional-info/venue-additional-info.test.js
test/unit/scripts/content-update.test.js

Dev -> Stage T3-25-13

---

events/blocks/event-subscription-form/event-subscription-form.css
events/blocks/event-subscription-form/event-subscription-form.js
package.json
test/unit/blocks/venue-additional-info/mocks/default.html
test/unit/blocks/venue-additional-info/venue-additional-info.test.js

Dev -> Stage 2025-4-3

---

events/blocks/event-agenda/event-agenda.js
events/blocks/event-map/event-map.js
events/blocks/event-partners/event-partners.js
events/blocks/event-schema/event-schema.js
events/blocks/events-form/events-form.js
events/blocks/profile-cards/profile-cards.js
events/blocks/venue-additional-info/venue-additional-info.js
events/scripts/content-update.js
events/scripts/scripts.js

Test URLs:
- After: https://lana-fix--events-milo--adobecom.aem.live/drafts/

Lana.log Fixes

---

events/scripts/content-update.js

Test URLs:
- After: https://misc-fixes--events-milo--adobecom.aem.live/drafts/

[Release path fix] Fixing RSVP button malfunctioning for returning users on event capacity

---

events/scripts/content-update.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-171080
Test URLs:
- After: https://rsvp-fix-again--events-milo--adobecom.aem.live/drafts/

RSVP fix #2

---

events/scripts/content-update.js

Fixes:
https://jira.corp.adobe.com/browse/MWPW-171080
Test URLs:
- Before: https://<BASE_BRANCH>--events-milo--adobecom.aem.live/drafts/
- After: https://<TARGET_BRANCH>--events-milo--adobecom.aem.live/drafts/

Fixing the modal using modal hash dataset

---

events/scripts/content-update.js

Test URLs:
- After: https://locale-refactor--events-milo--adobecom.aem.live/drafts/

Simplify Locale match code

---

helix-sitemap.yaml

Test URLs:
- After: https://helix-sitemap-change--events-milo--adobecom.aem.live/drafts/

Update helix-sitemap for de references

---

events/blocks/event-subscription-form/event-subscription-form.js

Resolves: [MWPW-169042](https://jira.corp.adobe.com/browse/MWPW-169042)
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.live/drafts/ambsingh/events-button
- After: https://ambsingh-sub-fix--events-milo--adobecom.aem.live/drafts/ambsingh/events-button

[MWPW-169042]fix email undefined issue

---

events/scripts/constances.js
events/scripts/content-update.js

Reverts adobecom/events-milo#306

Revert "Add content-update HTML support"

---

events/blocks/event-agenda/event-agenda.css

Resolves: [MWPW-172396](https://jira.corp.adobe.com/browse/MWPW-172396)
Test URLs:
- After: https://MWPW-172396--events-milo--adobecom.aem.live/drafts/

Fix Agenda block mobile padding

---

events/blocks/event-agenda/event-agenda.css
events/blocks/event-subscription-form/event-subscription-form.js
events/scripts/constances.js
events/scripts/content-update.js
tools/sidekick/config.json

T3.25.18 Dev -> Stage #1

---

events/blocks/events-form/events-form.js
events/scripts/content-update.js
events/scripts/dictionary-manager.js

Reverts adobecom/events-milo#301

Adding dictionary manager to localize RSVP fields

---

events/blocks/chrono-box/chrono-box.js
events/features/timing-framework/worker.js
events/scripts/content-update.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-173183
Test URLs:
- After: https://fix-html-population--events-milo--adobecom.aem.live/drafts/

Fix TF not loading first XF as default bug

---

events/blocks/chrono-box/chrono-box.css
events/blocks/chrono-box/chrono-box.js
events/blocks/events-form/events-form.js
events/features/milo-carousel.js
events/features/timing-framework/worker.js
events/scripts/content-update.js
events/scripts/dictionary-manager.js
events/scripts/utils.js
events/styles/styles.css
test/unit/scripts/content-update.test.js
tools/sidekick/config.json

Dev -> Stage T3-25.20

---

events/blocks/event-subscription-form/event-subscription-form.css
events/blocks/event-subscription-form/event-subscription-form.js

Resolves: https://jira.corp.adobe.com/browse/MWPW-173344
Test URLs:
- After: https://fix-sub-modal-layout--events-milo--adobecom.aem.live/drafts/

Unifying padding in thank you view

---

events/blocks/event-subscription-form/event-subscription-form.css
events/blocks/event-subscription-form/event-subscription-form.js

Unifying padding in thankyou view
Test URLs:

Unifying padding in thank you view (#318) Dev -> Stage

---

events/blocks/event-subscription-form/event-subscription-form.css
events/blocks/event-subscription-form/event-subscription-form.js

Fixes submission animation
Fixes container height unification issue
Fixes A11y
Fixes Form submission
Fixes mobile layout
Fixes broken profile email prepopulation
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.page/events
- After: https://mailing-modal-fix--events-milo--adobecom.aem.page/events

Fixing numerous event sub form issues

---

events/blocks/event-subscription-form/event-subscription-form.css
events/blocks/event-subscription-form/event-subscription-form.js
events/scripts/content-update.js

Test URLs:
- Before: https://main--events-milo--adobecom.aem.live/drafts/
- After: https://stage--events-milo--adobecom.aem.live/drafts/

Stage -> Main Subscription Form Fixes

---

events/scripts/scripts.js

Test URLs:
- After: https://fix-dot-html-assets--events-milo--adobecom.aem.live/drafts/

[stage hotfix] Fix dot html assets

---

events/blocks/event-subscription-form/event-subscription-form.css
events/blocks/event-subscription-form/event-subscription-form.js
events/scripts/content-update.js
helix-query.yaml
helix-sitemap.yaml

Dev -> Stage | June 13 | T3-25.25

---

helix-sitemap.yaml

Test URLs:
- Before: https://<BASE_BRANCH>--events-milo--adobecom.aem.live/drafts/
- After: https://<TARGET_BRANCH>--events-milo--adobecom.aem.live/drafts/

Stage -> Main for sitemap release

---

events/scripts/scripts.js
helix-sitemap.yaml

Resolves: [MWPW-175526](https://jira.corp.adobe.com/browse/MWPW-175526)
Test URLs:
- Before: https://main--events-milo--adobecom.aem.live/drafts/
- After: https://stage--events-milo--adobecom.aem.live/drafts/

Stage - Main noHtmlException Fix

---

docs/array-iteration-feature.md
events/scripts/content-update.js
events/scripts/utils.js
examples/array-iteration-example.html
test/unit/scripts/content-update.test.js

Resolves: [MWPW-175178](https://jira.corp.adobe.com/browse/MWPW-175178)
Test URLs:
- After: https://concat-syntax--events-milo--adobecom.aem.live/drafts/

Concat syntax

---

events/scripts/scripts.js

Test URLs:
- After: https://unused-profile-capture--events-milo--adobecom.aem.live/drafts/

Remove unnecessary attendee call on static pages

---

events/scripts/esp-controller.js

Test URLs:
- After: https://guest-reg-fix--events-milo--adobecom.aem.live/drafts/

Use attendee ID endpoint rather than me for Event/Attendee POST

---

events/scripts/esp-controller.js

Dev -> Stage Part 2 T3-25.28

---

events/scripts/esp-controller.js
events/scripts/scripts.js

404 change Dev -> Stage

---

events/blocks/mobile-rider/drawer.css
events/blocks/mobile-rider/drawer.js
events/blocks/mobile-rider/mobile-rider.css
events/blocks/mobile-rider/mobile-rider.js
test/unit/blocks/mobile-rider/drawer.test.js
test/unit/blocks/mobile-rider/mobile-rider.test.js

T3-25.31 Stage release

---

events/blocks/mobile-rider/drawer.css
events/blocks/mobile-rider/drawer.js
events/blocks/mobile-rider/mobile-rider.js
events/features/timing-framework/worker.js
events/scripts/content-update.js
test/unit/blocks/mobile-rider/drawer.test.js
test/unit/blocks/mobile-rider/mobile-rider.test.js

Test URLs:
- After: https://dev-fixes--events-milo--adobecom.aem.live/drafts/

Dev linting fixes + small typo fix

---

events/blocks/mobile-rider/drawer.css
events/blocks/mobile-rider/drawer.js
events/blocks/mobile-rider/mobile-rider.js
events/features/timing-framework/worker.js
events/scripts/content-update.js
test/unit/blocks/mobile-rider/drawer.test.js
test/unit/blocks/mobile-rider/mobile-rider.test.js

Reverts adobecom/events-milo#383

Revert "Dev -> Stage Patch"

---

events/blocks/mobile-rider/drawer.css
events/blocks/mobile-rider/drawer.js
events/blocks/mobile-rider/mobile-rider.js
events/features/timing-framework/worker.js
events/scripts/content-update.js
test/unit/blocks/mobile-rider/drawer.test.js
test/unit/blocks/mobile-rider/mobile-rider.test.js

Test URLs:
- After: https://stage--events-milo--adobecom.aem.live/drafts/

Minor Release T3-25.32

---

events/blocks/mobile-rider/drawer.js
events/blocks/mobile-rider/mobile-rider.js
events/blocks/youtube-chat/youtube-chat.js
test/unit/blocks/mobile-rider/drawer.test.js
test/unit/blocks/mobile-rider/mobile-rider.test.js
test/unit/blocks/youtube-chat/youtube-chat.test.js
test/unit/features/timing-framework/worker.test.js

Test URLs:
- Before: https://dev--events-milo--adobecom.aem.live/events/q-test-dme-template/q-test-chronobox/orlando/fl/us/2025-06-27?previewMode=true&cachebuster=1750780325358&timing=1751322600010
- After: https://linting--events-milo--adobecom.aem.live/events/q-test-dme-template/q-test-chronobox/orlando/fl/us/2025-06-27?previewMode=true&cachebuster=1750780325358&timing=1751322600010

[CHORE] Linting

---

events/blocks/mobile-rider/mobile-rider.js
events/features/timing-framework/plugins/mobile-rider/mobile-rider-controller.js
events/features/timing-framework/plugins/mobile-rider/plugin.js
events/features/timing-framework/worker.js
test/unit/blocks/mobile-rider/mobile-rider.test.js
test/unit/blocks/youtube-chat/youtube-chat.test.js

Minor fixes of store.
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.page/events/dme-timing-framework-test/test-dme-timing-framework/san-jose/ca/us/2025-08-29?previewMode=true&cachebuster=1754491900711
- After: https://newchronobox--events-milo--adobecom.aem.page/events/dme-timing-framework-test/test-dme-timing-framework/san-jose/ca/us/2025-08-29?previewMode=true&cachebuster=1754491900711

Mobile rider - Timing framework fixes

---

events/blocks/promotional-content/promotional-content.js
events/features/timing-framework/plugins/mobile-rider/plugin.js
events/features/timing-framework/worker.js
test/unit/blocks/promotional-content/mocks/default.html
test/unit/blocks/promotional-content/promotional-content.test.js

Resolves: [MWPW-176755](https://jira.corp.adobe.com/browse/MWPW-176755)
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.page/events/create-now/qiyun-testing-promotional-items/san-jose/ca/us/2025-08-21?previewMode=true
- After: https://promotional-content-fix--events-milo--adobecom.aem.page/events/create-now/qiyun-testing-promotional-items/san-jose/ca/us/2025-08-21?previewMode=true

Fixing promotional items hydration process

---

events/scripts/constances.js
events/scripts/content-update.js

Test URLs:
- After: https://test-email-domain--events-milo--adobecom.aem.live/drafts/

Added Test Automation Email Domain

---

events/blocks/event-product-blades/event-product-blades.css
events/blocks/event-product-blades/event-product-blades.js
test/unit/blocks/event-product-blades/event-product-blades.test.js

@adobetest.com added to previewMode whitelist

---

events/scripts/content-update.js

Test URLs:
- Before: https://dev--events-milo--adobecom.aem.live/events/create-now/test-dme-event-in-person/san-jose/ca/us/2025-10-25?previewMode=true&cachebuster=1759248075192&timing=1761427799990
- After: https://raise-metadata-query-limit--events-milo--adobecom.aem.live/events/create-now/test-dme-event-in-person/san-jose/ca/us/2025-10-25?previewMode=true&cachebuster=1759248075192&timing=1761427799990
For more information on how to set up ESL and ESP locally, please refer to: [FE Dev …

Raise Metadata Sheet Query Limit
