blocks/events-form/events-form.js, scripts/scripts.js, utils/event-apis.js
Describe your specific features or fixes:
Moving up mediator, and switch it from dynamic import to static. Block Mediator was taking longer to load and autolinks was not setting the `bm8r.susbcribe`
Resolves: [MWPW-145669](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
- Before: https://main--events-milo--adobecom.hlx.page/drafts/cano/details-page
- After: https://MWPW-145669--events-milo--adobecom.hlx.page/drafts/cano/details-page
=> MWPW-145669: move up mediator and change name

events/blocks/event-partners/event-partners.js
Remove getSponsor calls (unusable interim solution)
Updated checkbox value check
Resolves: [MWPW-148212](https://jira.corp.adobe.com/browse/MWPW-148212)
Test URLs:
- After: https://sponsors-refactor--events-milo--adobecom.hlx.page/
=> Sponsors Refactor

events/scripts/content-update.js, events/scripts/scripts.js
Fixes the issue where stage doesn't get a chance to populate metadata before redirect to 404 happens.
Fixes the issue where STRONG and EM tag placeholders can't be updated automatically
Test URLs:
- After: https://expand-content-replace--events-milo--adobecom.hlx.page/
=> stage.adobe.com redirect fix

events/blocks/event-agenda/event-agenda.js
Agenda block will now render time label locale sensitivity rather than using the metadata as-is
Resolves: [MWPW-153776](https://jira.corp.adobe.com/browse/MWPW-153776)
Test URLs:
- After: https://agenda-format-fix--events-milo--adobecom.hlx.page/
=> Event agenda time format localization

events/blocks/events-form/events-form.js, events/scripts/content-update.js, events/scripts/esp-controller.js, events/scripts/profile.js
Changes RSVP flow to use extra calls to get consistent rsvpData in BlockMediator. This is leveraging the new attendees/me/status endpoint Todd has enabled for us.
Resolves: [MWPW-148336](https://jira.corp.adobe.com/browse/MWPW-148336)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024/chicago/il/2024-08-04?martech=off
- After: https://rsvp-update--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024/chicago/il/2024-08-04?martech=off
=> RSVP response consistency update

events/blocks/event-map/event-map.js
As title. This is to help with the absolute venue-map-image url being loaded correctly on non-prod environments.
Test URLs:
=> make map sharepoint url relative

events/blocks/preview-bar/preview-bar.js, events/scripts/esp-controller.js
Fixing a wrong bool output from the preview bar condition check
Fixes a false negative console error caused by attendee fetch
Resolves: Pending [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Or we can refer to this one: [MWPW-153776](https://jira.corp.adobe.com/browse/MWPW-153776)
Test URLs:
- After: https://preview-bar-fix--events-milo--adobecom.hlx.page/
=> preview bar fix and a rogue console error fix

events/scripts/content-update.js
Resolves: no ticket
Once this is merged, https://main--events-milo--adobecom.hlx.page/events/create-now/test-event-pd/pleasant-grove/ut/2024-08-16?previewMode=true should show the page while https://main--events-milo--adobecom.hlx.page/events/create-now/test-event-pd/pleasant-grove/ut/2024-08-16 should redirect to 404
Test URLs:
- After: https://preview-hotfix--events-milo--adobecom.hlx.page/
=> Adobe IMSProfile based preview hotfix

events/blocks/events-form/events-form.css
Fixing spacing on events form hero
Before:
After
Test URLs:
- After: https://rsvp-form-spacing-tweak--events-milo--adobecom.hlx.page/
=> Tweaking Event Form Hero Spacing

events/scripts/esp-controller.js
Fixed a typo that caused brand new user registration to fail
Resolves: [MWPW-156179](https://jira.corp.adobe.com/browse/MWPW-156179)
Test URLs:
- After: https://rsvp-400--events-milo--adobecom.hlx.page/
=> Fixing RSVP refactor typo

events/blocks/events-form/events-form.js
Adds additional analytics to events-form on "Form View" and "Form Submission" 
To QA, use this [link](https://dev--events-milo--adobecom.hlx.page/events/create-now/create-now-chicago-2024-test/chicago/il/2024-07-27?timing=123 ) override the events-form.js code in browser (will need to click on "RSVP now" button once to get file to load). Type  _satellite.setDebug(true) in the console and then click the rsvp button. 
Look through the debugger data objects in the console to find new analytics name under web, webInteraction, linkClicks, name:
You should also see "Form Submission | Create Now Chicago 2024 Test | rsvp-form-1" if you click on the button to submit the form. 
Resolves: [MWPW-156794](https://jira.corp.adobe.com/browse/MWPW-156794)
Test URLs:
- Before: …
=> Add form view and form submission analytics

events/blocks/events-form/events-form.js
Adds Confirmation Modal View per John Wang's request. Changed "Form Submit" to "Form Submission" to match request in ticket and moved Form Submission analytics call up to ensure sequential firing of these new events ("Confirmation Modal View" now fires after "Form Submission" as expected).
Resolves: [MWPW-156794](https://jira.corp.adobe.com/browse/MWPW-156794)
Test URLs:
- After: https://confirmationmodalview--events-milo--adobecom.hlx.page/
=> Add confirmation modal view

events/blocks/preview-bar/preview-bar.js
Resolves: [MWPW-157576](https://jira.corp.adobe.com/browse/MWPW-157576)
Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/events/create-now/embrace-generative-ai-sep02/midvale/ut/2024-09-20?previewMode=true&cachebuster=1725391549880&timing=1726849799990
- After: https://MWPW-157576--events-milo--adobecom.hlx.page/events/create-now/embrace-generative-ai-sep02/midvale/ut/2024-09-20?previewMode=true&cachebuster=1725391549880&timing=1726849799990
=> [MWPW-157576] no longer change URL when bar removed

events/scripts/content-update.js, test/unit/scripts/content-update.test.js
Resolves: [MWPW-161149](https://jira.corp.adobe.com/browse/MWPW-161149)
Test URLs:
- After: https://waitlist-fix-2--events-milo--adobecom.hlx.page/
=> [MWPW-161149] Fix logged out user experience

events/blocks/profile-cards/profile-cards.js
Tightens the detection logic to look for "<platform-name>." in only the hostname
Resolves: [MWPW-161959](https://jira.corp.adobe.com/browse/MWPW-161959)
Test URLs:
https://www.adobe.com/events/creative-jam/creative-jam-phoenix/phoenix/az/2024-11-12.html
Can't be tested on different environments. You can use browser override and replace the events/blocks/profile-cards/profile-cards.js with the new version on this branch.
=> [Hotfix] Less false positive in link detection logic

events/blocks/event-map/event-map.css
Added a small padding to avoid mobile block collision when speakers are missing
Resolves: [MWPW-164922](https://jira.corp.adobe.com/browse/MWPW-164922)
Test URLs:
- After: https://jan-8-qa-fixes--events-milo--adobecom.hlx.page/
=> [CSS Tweak] Add a small padding to avoid block collision

.github/pull_request_template.md, events/blocks/event-map/event-map.css, events/blocks/events-form/events-form.js, events/blocks/profile-cards/profile-cards.js, events/scripts/esp-controller.js, events/scripts/utils.js
Test URLs:
- Before: https://stage--events-milo--adobecom.hlx.page/drafts/qiyundai/hub
- After: https://dev--events-milo--adobecom.hlx.page/drafts/qiyundai/hub
=>  Dev to Stage | Release | Dec 18

events/scripts/content-update.js
=> [Dev -> Stage] Parse URL before trying to find non-prod data (#216)

events/scripts/esp-controller.js
deleteAttendee call now expects empty response. Only the helper fetcher is changed. The block is expecting the same data.
Test URLs:
- After: https://MWPW-165501--events-milo--adobecom.hlx.page/
=> Change deleteAttendee call response handling

events/blocks/event-map/event-map.css, events/scripts/content-update.js
- Added helix-query change for consent string fragments
- Added response change handling for deleteAttendee call
Test URLs:
=> Dev -> Stage Jan 13th

events/scripts/content-update.js
Resolves: [MWPW-166938](https://jira.corp.adobe.com/browse/MWPW-166938)
Test URLs:
- After: https://use-series-data--events-milo--adobecom.aem.live/drafts/
=> [MWPW-166938] Use templateID as fallback while prioritising series data

events/blocks/events-form/events-form.js
Test URLs:
- After: https://consent-only-for-guest--events-milo--adobecom.aem.live/drafts/
=> Fix guest registration attr key for Consent loading

events/blocks/event-map/event-map.js, events/blocks/profile-cards/profile-cards.js
Test URLs:
- After: https://try-catch-blocks--events-milo--adobecom.aem.live/drafts/
=> Adding block self-destruct upon JSON parse failure

events/scripts/content-update.js
Test URLs:
- Before: https://main--events-milo--adobecom.aem.live/drafts/
- After: https://template-id-hotfix--events-milo--adobecom.aem.live/drafts/
=> [Hotfix] Template ID Regression

events/blocks/events-form/events-form.js
The ESP RSVP form is not loading dictionary values in the placeholders. This PR should fix that.
Before:
After:
Test URLs:
- After: https://dictionary-placeholder--events-milo--adobecom.aem.live/drafts/
=> Update placeholder with translation too

events/scripts/content-update.js
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.live/events/create-now/testing-seondary-cta/san-jose/ca/us/2025-05-16?previewMode=true&timing=1747542599990
- After: https://fix-double-replacement--events-milo--adobecom.aem.live/events/create-now/testing-seondary-cta/san-jose/ca/us/2025-05-16?previewMode=true&timing=1747542599990
=> Greedy replace to make sure no [[]] is left

events/scripts/content-update.js
=> Greedy replace to make sure no [[]] is left (#320) Dev -> Stage

helix-query.yaml, helix-sitemap.yaml
Test URLs:
- After: https://sitemap-update-for-extra-locale--events-milo--adobecom.aem.live/drafts/
=> Add sitemap config for added locales

events/scripts/scripts.js
=> Add noHtml Exception

events/blocks/chrono-box/chrono-box.js, events/features/timing-framework/worker.js
This is to fix the issue that condition based Timing framework detection can only check metadata's existence. The backend has a constraint where a removed video link from EMC will leave a video metadata tag on the page with an empty video url object: {"url": ""}. To fix that, the TF needs to learn to deep query metadata tags and understand empty objects and arrays as falsy.
Test URLs:
- After: https://chronobox-meta-deep-query--events-milo--adobecom.aem.live/drafts/
For more information on how to set up ESL and ESP locally, please refer to: [FE Dev Wiki](https://wiki.corp.adobe.com/display/adobedotcom/Events+Milo+FE+Dev+Wiki# …
=> Chronobox meta deep query

events/blocks/profile-cards/profile-cards.js
The 'x' platform has caused some false positive social platform recognition cases. We need a more robust way of handling the platform auto detection feature.
Test URLs:
- After: https://qiyundai-patch-1--events-milo--adobecom.aem.live/drafts/
=> Stricter Rules for social domain match

events/create-now/sitemap-index.xml, helix-query.yaml, helix-sitemap.yaml
Added UK
Added country-based sitemap hreflang
Revert to create-now sitemap location
Test URLs:
- Before: https://main--events-milo--adobecom.aem.live/drafts/
- After: https://sitemap-hotfix--events-milo--adobecom.aem.live/drafts/
=> Sitemap hotfix

events/scripts/scripts.js
Adding prodDomain constance according to Milo team's instruction to enabled #_dnt handle support.
Resolves: [MWPW-175962](https://jira.corp.adobe.com/browse/MWPW-175962)
Test URLs:
- After: https://prod-domain--events-milo--adobecom.aem.live/drafts/
=> ROW events migration - configure prodDomains

events/scripts/content-update.js
Making sure the captured RSVP state value is more up-to-date after the event data call.
Resolves: [MWPW-175192](https://jira.corp.adobe.com/browse/MWPW-175192)
Test URLs:
- After: https://smaller-rsvp-race-fix--events-milo--adobecom.aem.live/drafts/
=> Fixing the RSVP state in a simpler way

events/styles/styles.css
This update relinquishes our changes overriding the blue primary button on our page. The template docs have all be previewed/published again with the authoring approach (#_button-fill) to render black fill button. With this fix, the geo-routing modal will render with the standard S2 blue button rather than our black button.
Resolves: 
https://jira.corp.adobe.com/browse/MWPW-177299
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.page/de/events
- After: https://primary-button-color--events-milo--adobecom.aem.page/de/events
For more information on how to set up ESL and ESP locally, please refer to: [FE Dev Wiki](https://wiki.corp.adobe.com/display/adobedotcom/Events+Milo+FE+Dev …
=> Remove primary button CSS override

events/blocks/mobile-rider/mobile-rider.js
Mobile Rider player script URL path update.
Resolves: https://jira.corp.adobe.com/browse/MWPW-172648
Test URLs:
- Before: https://main--events-milo--adobecom.aem.page/drafts/hnv/test-mobile-rider-concurrent
- After: https://mobile-rider-script--events-milo--adobecom.aem.page/drafts/hnv/test-mobile-rider-concurrent
=> [MWPW-172648]:- Changed script source URL for Mobile Rider player

events/blocks/youtube-chat/youtube-chat.css, events/blocks/youtube-chat/youtube-chat.js, test/unit/blocks/youtube-chat/mocks/default.html, test/unit/blocks/youtube-chat/youtube-chat.test.js
Added support for displaying YouTube Chat next to the embedded YouTube Player block. This allows users to view and participate in the live chat directly within the MILO page.
Resolves: https://jira.corp.adobe.com/browse/MWPW-174658
Test URLs:
- Before: https://main--events-milo--adobecom.aem.live/drafts/hnv/youtube-chat-test
- After: https://youtube-chat-dev--events-milo--adobecom.aem.live/drafts/hnv/youtube-chat-test
Sample Authoring page:- https://adobe.sharepoint.com/:w:/r/sites/acomevents/_layouts/15/Doc.aspx?sourcedoc=%7B9584D062-49B8-4D07-AC98-4F5771C5C806%7D&file=youtube-chat-test.docx&action=default&mobileredirect=true
For more information on how to set up ESL and ESP locally, …
=> [MWPW-174658]:- Embed YouTube Chat Alongside Player Block in MILO

events/styles/styles.css
Added a way to have text and icon side by side in the Milo Text block
Resolves: [MWPW-176612](https://jira.corp.adobe.com/browse/MWPW-176612)
Sample authoring: https://adobe.sharepoint.com/:w:/r/sites/acomevents/_layouts/15/doc2.aspx?sourcedoc=%7B489A3CE1-767C-4072-806C-79856B2A1BA0%7D&file=editorial-card-mpc.docx&action=default&mobileredirect=true
Test URLs:
- Before: https://dev--events-milo--adobecom.aem.page/drafts/sharmeeb/fragments/editorial-card-mpc?martech=off
- After: https://mwpw-176612--events-milo--adobecom.aem.page/drafts/sharmeeb/fragments/editorial-card-mpc?martech=off
For more information on how to set up ESL and ESP locally, please refer to: [FE Dev …
=> [MWPW-176612] : [T1 migration] Add table styling for column text blocks

.github/workflows/run-e2e-tests.yml, .github/workflows/trigger-circleci.yml
This is similar to the Github workflow for ECC Milo: https://github.com/adobecom/ecc-milo/pull/556
To prevent redundant executions, this repository will not have a daily scheduled test run unlike ECC Milo.
Also, we will use the 'repository' parameter in our test repo's CircleCI config to conditionally run the appropriate test suite (such as the event-details tests) for the code changes in this repo.
Test results will also be sent to [#milo-events-tests](https://adobe.enterprise.slack.com/archives/C07DLEN78V9).
=> Add GitHub Actions workflows for E2E testing

events/blocks/promotional-content/promotional-content.js
Fixes a runtime error with malformed empty promotional content JSON data.
Test URLs:
- After: https://promotiona-content-fix--events-milo--adobecom.aem.live/drafts/
=> Prevent invalid promotional item mapping

events/blocks/events-form/events-form.js
As the error message changes, our 400 error handling for the user hitting the event full threshold is no longer working properly. 
The FE shouldn't have used error message to determine the kind of 400 error. This PR should fix this issue.
Resolves: [MWPW-180672](https://jira.corp.adobe.com/browse/MWPW-180672)
Test URLs:
- After: https://mwpw-180672--events-milo--adobecom.aem.live/drafts/
=> Fixing error message based ESP 400 error handling
